org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.java.installations.paths=/data/data/com.termux/files/usr/lib/jvm/java-25-openjdk
minecraft_version=26.1.2
loom_version=1.17.20
loader_version=0.19.5
fabric_api_version=0.155.3+26.1.2
mod_version=1.1.1-26.1.2
maven_group=cn.blockforge.generated
archives_base_name=sog_carpet
carpet_jar=libs/fabric-carpet-26.1+v260402.jar
